language: node_js
node_js:
  - node

jobs:
  include:

    - stage: lint
      script: npm run lint

    - stage: test
      script: npm run test

    - stage: coverage
      if: branch = master
      script: npm run coverage

    - stage: build
      script: npm run build

    - stage: npm release
      script: echo "Deploy MASTER to npm"
      if: branch = master
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_USER
        api_key: $NPM_TOKEN
          
notifications:
  email: false
