language: node_js
node_js:
  - node

jobs:
  include:

    - stage: lint
      script: npm run lint

    - stage: test
      script: npm run test

    - stage: coverage
      if: (tag =~ ^v) OR (branch = master)
      script: npm run coverage

    - stage: build
      if: (tag =~ ^v) OR (branch = master)
      script: npm run build

    - stage: npm release
      if: (tag =~ ^v) OR (branch = master)
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_USER
        api_key: $NPM_TOKEN
        
notifications:
  email: false
